### ISSUE TITLE
Check how content overflows are handled

### ISSUE THREAD

**Issue by mscroggs** [AVEgame/AVE-Flask#19]
We need to do the same checks on the website as in AVEgame/AVE#132:

> What happens if the room text is too long?
> 
> What happens if there are too many options?
> 
> What happens if the inventory is too long?

**Comment by mscroggs** [comment]
In Python, the overflows are handled by the Screen class, so we may need to adapt the javascript to handle these on the website

**Comment by Giannie** [comment]
Addressed in https://github.com/AVEgame/AVE-Flask/commit/f24f0193d06b29948b66731352c06cf0b37662ae

Overflow of options and text is handled with scrolling.

**Comment by Giannie** [comment]
Test and close if you are happy with behaviour.

**Comment by mscroggs** [comment]
nice work
