### ISSUE TITLE
Handle online repo for user games

### ISSUE THREAD

**Issue by Giannie** [AVEgame/AVE-Flask#3]
Read user games from online repo.

**Comment by mscroggs** [comment]
`.git/hooks/post-merge`

```
#!/bin/sh
python whateverthefileis.py
```

**Comment by mscroggs** [comment]
Here we make the gamelist (built in only):

https://github.com/AVEgame/AVE/blob/04ed63fc7e11fb0318b28ee53ca622cce165f8ff/ave/__main__.py#L16-L33

But it relies on having AVE installed.

This function loads the metadata so maybe we could copy this to avoid needs ave installed:
https://github.com/AVEgame/AVE/blob/04ed63fc7e11fb0318b28ee53ca622cce165f8ff/ave/parsing/game_loader.py#L46-L75
