### ISSUE TITLE
Add an upload feature for user games

### ISSUE THREAD

**Issue by Giannie** [AVEgame/AVE-Flask#5]
This is a necessary feature for v2.0

**Comment by Giannie** [comment]
Added, not fully tested

**Comment by Giannie** [comment]
Related to https://github.com/AVEgame/AVE-Flask/issues/12

**Comment by mscroggs** [comment]
The PR name for the upload must end with filename.ave so that AVEbot can work out which file to add comments on, eg https://github.com/AVEgame/AVE-usergames/pull/6#issuecomment-653819754

**Comment by Giannie** [comment]
@mscroggs It currently does that.

**Comment by mscroggs** [comment]
Thought so, but thought it best to remind future us that AVEbot uses the last word of the title to identify which game to leave comments on

**Comment by Giannie** [comment]
This now works, provided `"git_key"` is included in `config.json`
