### ISSUE TITLE
Increasing inventory numbers not working

### ISSUE THREAD

**Issue by Giannie** [AVEgame/AVE-Flask#6]
When increasing inventory numbers the following error is raised:

```
TypeError: unsupported operand type(s) for +=: 'int' and 'Constant'
```

I suspect we need to cast the integers passed in JSON into Constants.

@mscroggs Can you advise on how one constructs a Constant from an integer?

**Comment by mscroggs** [comment]
```
from ave.numbers import Constant
Constant(3)
Constant(1.5)
```

Alternatively you might need to do the following if ```change``` is a constant
```
inventory[i] += change.get_value(character)
```

(I'll take a better look at this after work)

**Comment by mscroggs** [comment]
This is now fixed in AVE
